In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = np.array([4,1,3,2,7,8,6])

In [3]:
np.partition(x,3)

array([1, 2, 3, 4, 7, 8, 6])

In [28]:
name = ["suneri","suma","chethan","julian","amanda"]
age = [25,26,26,30,28]
weight = [69,48,90,80,67]

In [29]:
data = np.zeros(5,dtype={"names":("name","age","weight"),
                        "formats":("U10","i4","f8")})

In [30]:
data['name']=name
data['age']=age
data['weight']=weight

In [31]:
data

array([('suneri', 25, 69.), ('suma', 26, 48.), ('chethan', 26, 90.),
       ('julian', 30, 80.), ('amanda', 28, 67.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
data[0]

('suneri', 25, 69.)

In [11]:
data[-1]['name']

'amanda'

In [14]:
data[data['age']<30]['name']

array(['suneri', 'suma', 'chethan', 'amanda'], dtype='<U10')

In [15]:
data = np.zeros(5,dtype={"names":("name","age","weight"),
                        "formats":((np.str_,10),int,np.float32)})

In [16]:
np.dtype([('name','S10'),('age','i4'),('weight','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [17]:
tp = np.dtype([('id','i8'),('mat','f8',(3,3))])

In [18]:
X = np.zeros(1,dtype=tp)

In [20]:
X[0]

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])

In [25]:
X['mat'][0]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
data_rec = data.view(np.recarray)

In [34]:
data_rec.age

array([25, 26, 26, 30, 28])

In [37]:
s1 = pd.Series([0.25,0.5,0.75,1])
s1

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [38]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [39]:
s1.values

array([0.25, 0.5 , 0.75, 1.  ])

In [40]:
s1[0]

0.25

In [41]:
s1[1:3]

1    0.50
2    0.75
dtype: float64

In [43]:
s2 = pd.Series([0.25,0.5,0.75,1],index=['a','b','c','d'])
print(s2)
print(s2.index)
print(s2.values)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
Index(['a', 'b', 'c', 'd'], dtype='object')
[0.25 0.5  0.75 1.  ]
