In [1]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
        
    return output

In [10]:
values = np.random.randint(1,10,size=5)
values1 = np.random.randint(1,100,size=100000)
values

array([7, 3, 2, 5, 4])

In [7]:
print(compute_reciprocals(values))

[0.25       0.16666667 0.33333333 0.2        0.125     ]


In [8]:
%timeit compute_reciprocals(values)

12.6 µs ± 782 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
%timeit compute_reciprocals(values1)

221 ms ± 25.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
%timeit 1.0/values1

215 µs ± 17.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
print(1.0/values)

[0.14285714 0.33333333 0.5        0.2        0.25      ]


In [15]:
print(np.arange(5))
print(np.arange(1,6))

[0 1 2 3 4]
[1 2 3 4 5]


In [14]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [17]:
grid1 = np.arange(9).reshape((3,3))
2**grid1

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [19]:
v1 = np.arange(5)
v1

array([0, 1, 2, 3, 4])

In [23]:
print(v1+5)
print(v1-10)
print(v1//2)
print(v1/2)

[5 6 7 8 9]
[-10  -9  -8  -7  -6]
[0 0 1 1 2]
[0.  0.5 1.  1.5 2. ]


In [24]:
np.add(2,v1)

array([2, 3, 4, 5, 6])

In [25]:
v2 = np.array([-1,6,-9,-0.5])
np.abs(v2)

array([1. , 6. , 9. , 0.5])