In [1]:
import pandas as pd
import numpy as np

In [2]:
population = {'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135
}

In [3]:
s1 = pd.Series(population)
s1['California']

38332521

In [4]:
s1['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [5]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [6]:
pd.Series({'a':1,'b':2,'c':3})

a    1
b    2
c    3
dtype: int64

In [7]:
pd.Series({'a':1,'b':2,'c':3}, index=['a','c'])

a    1
c    3
dtype: int64

In [8]:
area = {'California': 423967, 'Texas': 695662, 'New York': 141297,'Florida': 170312, 'Illinois': 149995}

In [9]:
df = pd.DataFrame({'population':population,'area':area})

In [10]:
df

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [11]:
df.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [12]:
df.columns

Index(['population', 'area'], dtype='object')

In [13]:
df['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [14]:
pd.DataFrame({'pop':population})

pop
California  38332521
Florida     19552860
Illinois    12882135
New York    19651127
Texas       26448193

In [15]:
data = [{'a':i,'b':2*i} for i in range(3)]

In [16]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [17]:
data1 = [{'a':2,'b':3},{'b':2,'c':8}]

In [18]:
pd.DataFrame(data1)

a  b    c
0  2.0  3  NaN
1  NaN  2  8.0

In [19]:
pd.DataFrame(np.random.rand(3,2), index=['a','b','c'],columns=["foo","bar"])

foo       bar
a  0.501220  0.275457
b  0.883774  0.965219
c  0.888951  0.241415

In [20]:
A = np.zeros(3, dtype=[('a','i8'),('b','f8')])

In [21]:
pd.DataFrame(A)

a    b
0  0  0.0
1  0  0.0
2  0  0.0

In [22]:
ind = pd.Index([2,3,4,5])
ind

Int64Index([2, 3, 4, 5], dtype='int64')

In [23]:
ind[1]

3

In [24]:
ind[::2]

Int64Index([2, 4], dtype='int64')

In [25]:
ind.dtype

dtype('int64')

In [26]:
ind.size

4

In [27]:
ind.ndim

1

In [28]:
ind.shape

(4,)

In [30]:
ind[1]=0

TypeError: Index does not support mutable operations

In [31]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [32]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [33]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [34]:
indA & indB

C:\Users\SKUP\AppData\Local\Temp/ipykernel_17880/144964795.py:1: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  indA & indB


Int64Index([3, 5, 7], dtype='int64')

In [35]:
indA ^ indB

C:\Users\SKUP\AppData\Local\Temp/ipykernel_17880/2832893868.py:1: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  indA ^ indB


Int64Index([1, 2, 9, 11], dtype='int64')

In [36]:
data = pd.Series([0.25,0.5,0.75,1],index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [37]:
data['e'] = 1.25

In [38]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [39]:
data['a']

0.25

In [40]:
'a' in data

True

In [41]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [42]:
data.values

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [43]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0), ('e', 1.25)]

In [44]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [45]:
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [46]:
data[(data>0.3) & (data<0.7)]

b    0.5
dtype: float64

In [47]:
data[['a','e']]

a    0.25
e    1.25
dtype: float64

In [48]:
data1 = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data1

1    a
3    b
5    c
dtype: object

In [49]:
data1[1]

'a'

In [50]:
data1[1:3]

3    b
5    c
dtype: object

In [51]:
data1.loc[1]

'a'

In [52]:
data1.loc[1:3]

1    a
3    b
dtype: object

In [53]:
data1.iloc[1]

'b'

In [54]:
data1.iloc[1:3]

3    b
5    c
dtype: object

In [55]:
area = pd.Series({'California': 423967, 'Texas': 695662,
 'New York': 141297, 'Florida': 170312,
 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127, 'Florida': 19552860,
 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [56]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [57]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [58]:
data.area is data['area']

True

In [59]:
data.pop is data['pop']

False

In [60]:
data['density'] = data['pop']/data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [61]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [62]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [63]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [64]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [65]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [66]:
data.loc['New York':'Illinois',:'density']

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [67]:
data.loc[data.density>100,['pop','density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [68]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [69]:
data.iloc[0,2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [70]:
data[data.density>100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [72]:
rng = np.random.RandomState(42)
pd.Series(rng.randint(0,10,4))

0    6
1    3
2    7
3    4
dtype: int32

In [75]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns=['A','B','C','D'])
df

A  B  C  D
0  6  3  8  2
1  4  2  6  4
2  8  6  1  3

In [76]:
np.exp(df)

A           B            C          D
0   403.428793   20.085537  2980.957987   7.389056
1    54.598150    7.389056   403.428793  54.598150
2  2980.957987  403.428793     2.718282  20.085537

In [77]:
np.sin(df*np.pi/4)

A         B             C             D
0 -1.000000e+00  0.707107 -2.449294e-16  1.000000e+00
1  1.224647e-16  1.000000 -1.000000e+00  1.224647e-16
2 -2.449294e-16 -1.000000  7.071068e-01  7.071068e-01

In [78]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127}, name='population')

In [79]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [81]:
population.index | area.index

C:\Users\SKUP\AppData\Local\Temp/ipykernel_17880/3714857733.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  population.index | area.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [84]:
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index=[1,2,3])

In [85]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [87]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [88]:
A1 = pd.DataFrame(rng.randint(0,10,(2,2)),columns=list('AB'))
B1 = pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('BAC'))

In [89]:
A1+B1

A     B   C
0  12.0  10.0 NaN
1  15.0  11.0 NaN
2   NaN   NaN NaN

In [91]:
A1.add(B1,fill_value='0')

A     B    C
0  12.0  10.0  1.0
1  15.0  11.0  7.0
2   0.0   2.0  3.0

In [97]:
fill = A1.stack().mean()
A1.add(B1,fill_value=fill)

A     B     C
0  12.0  10.0   7.5
1  15.0  11.0  13.5
2   6.5   8.5   9.5

In [98]:
A2 = rng.randint(0,10,(3,4))
A2

array([[1, 7, 3, 1],
       [5, 5, 9, 3],
       [5, 1, 9, 1]])

In [99]:
A2 - A2[0]

array([[ 0,  0,  0,  0],
       [ 4, -2,  6,  2],
       [ 4, -6,  6,  0]])

In [100]:
df2 = pd.DataFrame(A2,columns=list('QRST'))
df2

Q  R  S  T
0  1  7  3  1
1  5  5  9  3
2  5  1  9  1

In [102]:
df2 - df2.iloc[0]

Q  R  S  T
0  0  0  0  0
1  4 -2  6  2
2  4 -6  6  0

In [103]:
df2.subtract(df2['R'],axis=0)

Q  R  S  T
0 -6  0 -4 -6
1  0  0  4 -2
2  4  0  8  0

In [106]:
half = df2.iloc[0,::2]
half

Q    1
S    3
Name: 0, dtype: int32

In [107]:
df2 - half

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  4.0 NaN  6.0 NaN
2  4.0 NaN  6.0 NaN

In [108]:
pd.Series([2,None,5,np.NaN])

0    2.0
1    NaN
2    5.0
3    NaN
dtype: float64

In [110]:
x = pd.Series(range(2),dtype=int)
x

0    0
1    1
dtype: int32

In [111]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [112]:
data = pd.Series([1,np.nan,2,None,5,6,7])
data.isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
dtype: bool

In [113]:
data[data.notnull()]

0    1.0
2    2.0
4    5.0
5    6.0
6    7.0
dtype: float64

In [114]:
data.dropna()

0    1.0
2    2.0
4    5.0
5    6.0
6    7.0
dtype: float64

In [124]:
df = pd.DataFrame([[1, np.nan, 2],[2, 3, 5],[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [118]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [120]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [125]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [123]:
df.dropna(axis="columns",how="all")

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [126]:
df.dropna(axis="rows",thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [132]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [129]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [131]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [133]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [134]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [137]:
df.fillna(axis="columns",method='ffill')

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [138]:
index = [('California', 2000), ('California', 2010),
 ('New York', 2000), ('New York', 2010),
 ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
 18976457, 19378102,
 20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [139]:
pop[("California",2010):("New York",2010)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
dtype: int64

In [141]:
pop[[i for i in pop.index if i[1]==2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [143]:
indx = pd.MultiIndex.from_tuples(index)
indx

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [145]:
pop = pop.reindex(indx)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [146]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [147]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [148]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [149]:
pop_df = pd.DataFrame({'total': pop,
 'under18': [9267089, 9284094,
 4687374, 4318033,
 5906301, 6879014]})

pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [150]:
f_u18 = pop_df['under18']/pop_df['total']
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [151]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [152]:
df = pd.DataFrame(np.random.rand(4,2),index=[['a','a','b','b'],[1,2,1,2]],columns=['data1','data2'])
df

data1     data2
a 1  0.837034  0.249359
  2  0.717337  0.145302
b 1  0.844168  0.778038
  2  0.629162  0.245435

In [154]:
data = {('california',2000):33871648,
       ('california',2010):37253956,
       ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561}

df = pd.Series(data)
df

california  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [156]:
pop.index.names = ["country","year"]
pop

country     year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [157]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=["year","visit"])
columns = pd.MultiIndex.from_product([["Bob","Guido","Sue"],["HR","Temp"]],names=["subject","type"])

In [158]:
data = np.round(np.random.randn(4,6),1)
data[:,::2]*=10
data+=37

In [160]:
health_data = pd.DataFrame(data,index=index,columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      44.0  36.4  38.0  36.1  36.0  35.2
     2      38.0  36.5  35.0  36.0   6.0  36.6
2014 1      50.0  37.6  50.0  36.7  23.0  36.3
     2      28.0  36.6  48.0  35.1  52.0  37.8

In [161]:
health_data["Guido"]

type          HR  Temp
year visit            
2013 1      38.0  36.1
     2      35.0  36.0
2014 1      50.0  36.7
     2      48.0  35.1

In [162]:
pop

country     year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [163]:
pop['California',2000]

33871648

In [164]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [165]:
pop.loc["California":"New York"]

country     year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [166]:
pop[:,2000]

country
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [167]:
pop[pop>22000000]

country     year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [168]:
pop[["California","Texas"]]

country     year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [169]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      44.0  36.4  38.0  36.1  36.0  35.2
     2      38.0  36.5  35.0  36.0   6.0  36.6
2014 1      50.0  37.6  50.0  36.7  23.0  36.3
     2      28.0  36.6  48.0  35.1  52.0  37.8

In [171]:
health_data["Guido","HR"]

year  visit
2013  1        38.0
      2        35.0
2014  1        50.0
      2        48.0
Name: (Guido, HR), dtype: float64

In [173]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      44.0  36.4
     2      38.0  36.5

In [174]:
health_data.loc[:,("Bob","HR")]

year  visit
2013  1        44.0
      2        38.0
2014  1        50.0
      2        28.0
Name: (Bob, HR), dtype: float64

In [175]:
idx = pd.IndexSlice

In [177]:
health_data.loc[idx[:,1],idx[:,"HR"]]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      44.0  38.0  36.0
2014 1      50.0  50.0  23.0