In [3]:
L = list(range(5))

In [4]:
L

[0, 1, 2, 3, 4]

In [5]:
type(L)

list

In [6]:
type(L[0])

int

In [7]:
L2 = list(str(range(5)))

In [8]:
type(L2)

list

In [9]:
type(L2[0])

str

In [10]:
L3 = [True, 3,3.0, "3.0"]

In [11]:
type(L3)

list

In [12]:
l4 = [type(item) for item in L3]

In [13]:
l4

[bool, int, float, str]

In [14]:
import array

In [15]:
L = list(range(10))

In [16]:
L1 = array.array('i',L)

In [17]:
L1

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
import numpy as np

In [19]:
L2 = np.array([1,2,3,4,5])

In [20]:
L2

array([1, 2, 3, 4, 5])

In [21]:
L3 = np.array([3.0,2,4.0,7])

In [22]:
L3

array([3., 2., 4., 7.])

In [23]:
L4 = np.array([4,5,6,7],dtype="float32")

In [24]:
L4

array([4., 5., 6., 7.], dtype=float32)

In [27]:
L5 = np.array([range(i,i+3) for i in [2,3,4]])

In [28]:
L5

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [29]:
np.zeros((10,),dtype="float32")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [30]:
np.ones((2,2),dtype="float32")

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [31]:
np.full((2,2),fill_value=3.1)

array([[3.1, 3.1],
       [3.1, 3.1]])

In [32]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [33]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.random.random((2,2))

array([[0.76691706, 0.243772  ],
       [0.83545162, 0.18507247]])

In [35]:
np.random.normal(0,1,(3,3))

array([[ 0.06307096,  0.68889695,  0.34891097],
       [ 0.74744642,  0.93852311, -0.45344713],
       [-0.86005332, -0.87015354, -1.02977531]])

In [36]:
np.random.randint(0,10,(3,3))

array([[8, 1, 0],
       [5, 8, 1],
       [2, 0, 5]])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.empty(3)

array([1.33047156e-311, 0.00000000e+000, 9.13565187e+242])

In [40]:
np.zeros(10,np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [43]:
a1 = np.random.randint(10,size=6)
a1

array([7, 9, 2, 7, 4, 5])

In [47]:
a2 = np.random.randint(10,size=(3,3))
a2

array([[9, 1, 7],
       [2, 8, 7],
       [4, 9, 1]])

In [50]:
a3 = np.random.randint(10,size=(2,3,4))
a3

array([[[4, 2, 5, 5],
        [0, 4, 0, 4],
        [8, 9, 9, 3]],

       [[7, 7, 1, 1],
        [4, 8, 8, 7],
        [3, 3, 1, 0]]])

In [54]:
print(a1.shape,a2.shape, a3.shape)
print(a1.ndim,a2.ndim,a3.ndim)
print(a1.size,a2.size,a3.size)

(6,) (3, 3) (2, 3, 4)
1 2 3
6 9 24


In [55]:
a1.itemsize*a1.size

24

In [56]:
a1.nbytes

24

In [58]:
a1, a1[0],a1[1],a1[-1],a1[-2]

(array([7, 9, 2, 7, 4, 5]), 7, 9, 5, 4)

In [63]:
a2, a2[0][0],a2[0,0],a2[2][0],a2[2][-1]

(array([[9, 1, 7],
        [2, 8, 7],
        [4, 9, 1]]),
 9,
 9,
 4,
 1)

In [64]:
a2[1,2] = 0

In [65]:
a2

array([[9, 1, 7],
       [2, 8, 0],
       [4, 9, 1]])

In [66]:
x = np.arange(10)

In [70]:
x,x[5:], x[:5],x[2:6]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([5, 6, 7, 8, 9]),
 array([0, 1, 2, 3, 4]),
 array([2, 3, 4, 5]))

In [77]:
x,x[::2],x[::-2],x[1::2],x[::-1],x[5::-2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0, 2, 4, 6, 8]),
 array([9, 7, 5, 3, 1]),
 array([1, 3, 5, 7, 9]),
 array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]),
 array([5, 3, 1]))