In [1]:
import numpy as np

In [5]:
x = np.random.randint(0,10,size=(3,4))
x

array([[3, 4, 9, 4],
       [9, 8, 5, 8],
       [0, 6, 2, 8]])

In [7]:
x[:2,:3]

array([[3, 4, 9],
       [9, 8, 5]])

In [9]:
x[:,::2]

array([[3, 9],
       [9, 5],
       [0, 2]])

In [10]:
x[::-1,::-1]

array([[8, 2, 6, 0],
       [8, 5, 8, 9],
       [4, 9, 4, 3]])

In [11]:
x[:,0]

array([3, 9, 0])

In [12]:
x[0,:]

array([3, 4, 9, 4])

In [14]:
x_sub = x[:2, :2]
x_sub

array([[3, 4],
       [9, 8]])

In [16]:
x_sub[0,0] = 99
x_sub

array([[99,  4],
       [ 9,  8]])

In [17]:
x

array([[99,  4,  9,  4],
       [ 9,  8,  5,  8],
       [ 0,  6,  2,  8]])

In [22]:
x2 = np.random.randint(0,10,size=(3,4))

In [23]:
x2_sub = x2[:2,:2].copy()

In [24]:
x2_sub[0,0] = 99
x2_sub

array([[99,  0],
       [ 6,  9]])

In [25]:
x2

array([[6, 0, 0, 0],
       [6, 9, 4, 1],
       [4, 3, 3, 4]])

In [31]:
a1 = np.arange(1,10)
a1 = a1.reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a2 = np.array([1,2,3])
a2 = a2.reshape(3,1)
a2

array([[1],
       [2],
       [3]])

In [34]:
a2[np.newaxis,:]

array([[[1],
        [2],
        [3]]])

In [35]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [37]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [38]:
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [40]:
grid = np.random.randint(1,10,size=(3,3))
grid

array([[2, 8, 6],
       [8, 1, 7],
       [3, 1, 3]])

In [41]:
np.concatenate([grid,grid])

array([[2, 8, 6],
       [8, 1, 7],
       [3, 1, 3],
       [2, 8, 6],
       [8, 1, 7],
       [3, 1, 3]])

In [42]:
np.concatenate([grid,grid],axis=1)

array([[2, 8, 6, 2, 8, 6],
       [8, 1, 7, 8, 1, 7],
       [3, 1, 3, 3, 1, 3]])

In [44]:
x = np.array([1,2,3])

y = np.array([[4,5,6],
             [7,8,9]])
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
x1 = np.array([[1],
               [2]])

In [52]:
np.hstack([x1,y])

array([[1, 4, 5, 6],
       [2, 7, 8, 9]])

In [53]:
x3 = [1, 2, 3, 99, 99, 3, 2, 1]

In [55]:
res1,res2,res3 = np.split(x3,[3,5])
print(res1)
print(res2)
print(res3)

[1 2 3]
[99 99]
[3 2 1]


In [57]:
grid1 = np.arange(16).reshape((4,4))
grid1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
upper,lower = np.vsplit(grid1,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [59]:
left,right = np.hsplit(grid1,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
